global:
  namespace: rse
oc:
  image: quay.io/openshift/origin-cli:latest
  serviceaccount: rse-installer
postgres:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi9-17.6-2534
ibm:
  entitlement: eHh4eHh4eHh4eHh4eHh4Cg==
